import { PortalRolle, Berechtigung } from '../../models/user.model';
import { AuditEntry } from './audit-tab.component';

export const ROLLEN: PortalRolle[] = [
  { id: 'r1', name: 'Administrator', beschreibung: 'Vollzugriff auf alle Systembereiche und Konfigurationen', hierarchie: 1, berechtigungIds: ['p1','p2','p3','p4','p5','p6','p7','p8','p9','p10'], scope: 'global', benutzerAnzahl: 3, systemRolle: true, farbe: '#CC3333' },
  { id: 'r2', name: 'Sachbearbeiter', beschreibung: 'Fallbearbeitung und Standardvorgaenge', hierarchie: 3, berechtigungIds: ['p1','p5','p11','p12','p13'], scope: 'mandant', benutzerAnzahl: 4, systemRolle: false, farbe: '#006EC7' },
  { id: 'r3', name: 'Teamleiter', beschreibung: 'Teamverwaltung und erweiterte Bearbeitungsrechte', hierarchie: 2, berechtigungIds: ['p1','p2','p5','p6','p11','p12','p14','p15'], scope: 'mandant', benutzerAnzahl: 3, systemRolle: false, farbe: '#28DCAA' },
  { id: 'r4', name: 'Pruefer', beschreibung: 'Pruefung und Freigabe von Vorgaengen', hierarchie: 4, berechtigungIds: ['p1','p5','p16','p17','p18'], scope: 'mandant', benutzerAnzahl: 3, systemRolle: false, farbe: '#FF9868' },
  { id: 'r5', name: 'Abrechnungsexperte', beschreibung: 'Abrechnungsprozesse und Finanzauswertungen', hierarchie: 3, berechtigungIds: ['p1','p19','p20','p21','p22'], scope: 'mandant', benutzerAnzahl: 2, systemRolle: false, farbe: '#F566BA' },
  { id: 'r6', name: 'Lesebenutzer', beschreibung: 'Nur lesender Zugriff auf freigegebene Bereiche', hierarchie: 5, berechtigungIds: ['p1','p5','p11'], scope: 'eingeschraenkt', benutzerAnzahl: 2, systemRolle: true, farbe: '#887D75' },
  { id: 'r7', name: 'API-Integration', beschreibung: 'Technischer Zugang fuer Schnittstellenanbindung', hierarchie: 6, berechtigungIds: ['p23','p24','p25','p26'], scope: 'technisch', benutzerAnzahl: 2, systemRolle: true, farbe: '#461EBE' },
];

export const BERECHTIGUNGEN: Berechtigung[] = [
  { id: 'p1', key: 'portal.dashboard.lesen', label: 'Dashboard anzeigen', beschreibung: '', typ: 'lesen', appId: 'portal', appName: 'Portal', gruppe: 'Dashboard' },
  { id: 'p2', key: 'portal.dashboard.schreiben', label: 'Dashboard konfigurieren', beschreibung: '', typ: 'schreiben', appId: 'portal', appName: 'Portal', gruppe: 'Dashboard' },
  { id: 'p3', key: 'portal.benutzer.schreiben', label: 'Benutzer verwalten', beschreibung: '', typ: 'schreiben', appId: 'portal', appName: 'Portal', gruppe: 'Benutzerverwaltung' },
  { id: 'p4', key: 'portal.benutzer.loeschen', label: 'Benutzer loeschen', beschreibung: '', typ: 'loeschen', appId: 'portal', appName: 'Portal', gruppe: 'Benutzerverwaltung' },
  { id: 'p5', key: 'portal.nachrichten.lesen', label: 'Nachrichten lesen', beschreibung: '', typ: 'lesen', appId: 'portal', appName: 'Portal', gruppe: 'Nachrichten' },
  { id: 'p6', key: 'portal.nachrichten.schreiben', label: 'Nachrichten senden', beschreibung: '', typ: 'schreiben', appId: 'portal', appName: 'Portal', gruppe: 'Nachrichten' },
  { id: 'p7', key: 'portal.parameter.schreiben', label: 'Parameter aendern', beschreibung: '', typ: 'schreiben', appId: 'portal', appName: 'Portal', gruppe: 'Parameter' },
  { id: 'p8', key: 'portal.parameter.admin', label: 'Parameter administrieren', beschreibung: '', typ: 'admin', appId: 'portal', appName: 'Portal', gruppe: 'Parameter' },
  { id: 'p9', key: 'portal.rollen.admin', label: 'Rollen verwalten', beschreibung: '', typ: 'admin', appId: 'portal', appName: 'Portal', gruppe: 'Rollen' },
  { id: 'p10', key: 'portal.audit.lesen', label: 'Audit-Trail einsehen', beschreibung: '', typ: 'lesen', appId: 'portal', appName: 'Portal', gruppe: 'Audit' },
  { id: 'p11', key: 'smile.faelle.lesen', label: 'Faelle anzeigen', beschreibung: '', typ: 'lesen', appId: 'smile', appName: 'SMILE KH', gruppe: 'Fallmanagement' },
  { id: 'p12', key: 'smile.faelle.schreiben', label: 'Faelle bearbeiten', beschreibung: '', typ: 'schreiben', appId: 'smile', appName: 'SMILE KH', gruppe: 'Fallmanagement' },
  { id: 'p13', key: 'smile.faelle.loeschen', label: 'Faelle loeschen', beschreibung: '', typ: 'loeschen', appId: 'smile', appName: 'SMILE KH', gruppe: 'Fallmanagement' },
  { id: 'p14', key: 'smile.team.lesen', label: 'Team anzeigen', beschreibung: '', typ: 'lesen', appId: 'smile', appName: 'SMILE KH', gruppe: 'Teamverwaltung' },
  { id: 'p15', key: 'smile.team.schreiben', label: 'Team verwalten', beschreibung: '', typ: 'schreiben', appId: 'smile', appName: 'SMILE KH', gruppe: 'Teamverwaltung' },
  { id: 'p16', key: 'smile.pruefung.lesen', label: 'Pruefungen anzeigen', beschreibung: '', typ: 'lesen', appId: 'smile', appName: 'SMILE KH', gruppe: 'Pruefung' },
  { id: 'p17', key: 'smile.pruefung.schreiben', label: 'Pruefungen durchfuehren', beschreibung: '', typ: 'schreiben', appId: 'smile', appName: 'SMILE KH', gruppe: 'Pruefung' },
  { id: 'p18', key: 'smile.pruefung.freigabe', label: 'Pruefungen freigeben', beschreibung: '', typ: 'admin', appId: 'smile', appName: 'SMILE KH', gruppe: 'Pruefung' },
  { id: 'p19', key: 'abrechnung.rechnungen.lesen', label: 'Rechnungen anzeigen', beschreibung: '', typ: 'lesen', appId: 'abrechnung', appName: 'Abrechnung', gruppe: 'Rechnungen' },
  { id: 'p20', key: 'abrechnung.rechnungen.schreiben', label: 'Rechnungen erstellen', beschreibung: '', typ: 'schreiben', appId: 'abrechnung', appName: 'Abrechnung', gruppe: 'Rechnungen' },
  { id: 'p21', key: 'abrechnung.auswertung.lesen', label: 'Auswertungen anzeigen', beschreibung: '', typ: 'lesen', appId: 'abrechnung', appName: 'Abrechnung', gruppe: 'Auswertung' },
  { id: 'p22', key: 'abrechnung.auswertung.export', label: 'Auswertungen exportieren', beschreibung: '', typ: 'schreiben', appId: 'abrechnung', appName: 'Abrechnung', gruppe: 'Auswertung' },
  { id: 'p23', key: 'api.rest.lesen', label: 'REST API lesen', beschreibung: '', typ: 'lesen', appId: 'api', appName: 'API Gateway', gruppe: 'REST' },
  { id: 'p24', key: 'api.rest.schreiben', label: 'REST API schreiben', beschreibung: '', typ: 'schreiben', appId: 'api', appName: 'API Gateway', gruppe: 'REST' },
  { id: 'p25', key: 'api.webhook.lesen', label: 'Webhooks anzeigen', beschreibung: '', typ: 'lesen', appId: 'api', appName: 'API Gateway', gruppe: 'Webhooks' },
  { id: 'p26', key: 'api.webhook.schreiben', label: 'Webhooks verwalten', beschreibung: '', typ: 'schreiben', appId: 'api', appName: 'API Gateway', gruppe: 'Webhooks' },
  { id: 'p27', key: 'wb.antraege.lesen', label: 'Antraege anzeigen', beschreibung: '', typ: 'lesen', appId: 'wb', appName: 'WB-Foerderung', gruppe: 'Antraege' },
  { id: 'p28', key: 'wb.antraege.schreiben', label: 'Antraege bearbeiten', beschreibung: '', typ: 'schreiben', appId: 'wb', appName: 'WB-Foerderung', gruppe: 'Antraege' },
  { id: 'p29', key: 'wb.foerderung.lesen', label: 'Foerderungen anzeigen', beschreibung: '', typ: 'lesen', appId: 'wb', appName: 'WB-Foerderung', gruppe: 'Foerderung' },
  { id: 'p30', key: 'wb.foerderung.admin', label: 'Foerderungen verwalten', beschreibung: '', typ: 'admin', appId: 'wb', appName: 'WB-Foerderung', gruppe: 'Foerderung' },
  { id: 'p31', key: 'arzt.register.lesen', label: 'Arztregister einsehen', beschreibung: '', typ: 'lesen', appId: 'arzt', appName: 'Arztregister', gruppe: 'Register' },
];

export const AUDIT_TRAIL: AuditEntry[] = [
  { id: 'a1', timestamp: '2026-03-12 11:30:00', action: 'login', beschreibung: 'Erfolgreicher Login', benutzer: 'Michael Braun', ausgefuehrtVon: 'Michael Braun' },
  { id: 'a2', timestamp: '2026-03-12 10:05:00', action: 'login', beschreibung: 'Erfolgreicher Login', benutzer: 'Thomas Fischer', ausgefuehrtVon: 'Thomas Fischer' },
  { id: 'a3', timestamp: '2026-03-12 09:15:00', action: 'geaendert', beschreibung: 'Rolle Sachbearbeiter zugewiesen', benutzer: 'Anna Schneider', ausgefuehrtVon: 'Anna Schneider' },
  { id: 'a4', timestamp: '2026-03-11 17:30:00', action: 'login', beschreibung: 'Erfolgreicher Login', benutzer: 'Laura Mueller', ausgefuehrtVon: 'Laura Mueller' },
  { id: 'a5', timestamp: '2026-03-11 16:10:00', action: 'geaendert', beschreibung: 'E-Mail-Adresse aktualisiert', benutzer: 'Petra Klein', ausgefuehrtVon: 'Anna Schneider' },
  { id: 'a6', timestamp: '2026-03-10 14:22:00', action: 'erstellt', beschreibung: 'Benutzer angelegt', benutzer: 'Sandra Becker', ausgefuehrtVon: 'Anna Schneider' },
  { id: 'a7', timestamp: '2026-03-09 09:45:00', action: 'login', beschreibung: 'Erfolgreicher Login', benutzer: 'Claudia Wolf', ausgefuehrtVon: 'Claudia Wolf' },
  { id: 'a8', timestamp: '2026-03-08 11:00:00', action: 'gesperrt', beschreibung: 'Benutzer gesperrt wegen Verdacht', benutzer: 'Nicole Richter', ausgefuehrtVon: 'Anna Schneider' },
  { id: 'a9', timestamp: '2026-03-07 15:30:00', action: 'geaendert', beschreibung: 'Passwort zurueckgesetzt', benutzer: 'Stefan Schulz', ausgefuehrtVon: 'Anna Schneider' },
  { id: 'a10', timestamp: '2026-03-06 09:00:00', action: 'erstellt', beschreibung: 'Rolle API-Integration erstellt', benutzer: '-', ausgefuehrtVon: 'Anna Schneider' },
  { id: 'a11', timestamp: '2026-03-05 13:15:00', action: 'geaendert', beschreibung: 'Mandant geaendert', benutzer: 'Jan Hoffmann', ausgefuehrtVon: 'Laura Mueller' },
  { id: 'a12', timestamp: '2026-03-04 10:45:00', action: 'geloescht', beschreibung: 'Testbenutzer entfernt', benutzer: 'Test User', ausgefuehrtVon: 'Anna Schneider' },
  { id: 'a13', timestamp: '2026-03-03 16:00:00', action: 'entsperrt', beschreibung: 'Benutzer entsperrt', benutzer: 'Markus Weber', ausgefuehrtVon: 'Laura Mueller' },
  { id: 'a14', timestamp: '2026-03-02 08:30:00', action: 'erstellt', beschreibung: 'Berechtigung wb.foerderung.admin hinzugefuegt', benutzer: '-', ausgefuehrtVon: 'Anna Schneider' },
  { id: 'a15', timestamp: '2026-03-01 14:00:00', action: 'geaendert', beschreibung: 'Status auf inaktiv gesetzt', benutzer: 'Stefan Schulz', ausgefuehrtVon: 'Anna Schneider' },
];
