package de.adesso.health.portal.enums;

public enum MarketSegment {
    STEUERUNG_PRUEFSTELLEN,
    KOSTENTRAEGER,
    ABRECHNUNGSDIENSTLEISTER,
    LEISTUNGSERBRINGER,
    INFRASTRUKTUR_PLATTFORMEN,
    OEFFENTLICHE_HAND_FORSCHUNG
}
